{
 "title": "AgroSentinel.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "🟢 Panel 1: Los Indicadores KPI",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "agro_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  temperatura\nFROM mediciones_clima\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "💧 Humedad Relativa",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "agro_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  temperatura,\n  humedad\nFROM mediciones_clima\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "indicador VPD",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "agro_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  (0.6108 * exp((17.27 * temperatura) / (temperatura + 237.3)) * (1 - (humedad / 100))) AS \"VPD (kPa)\"\nFROM mediciones_clima\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "💧 Punto de Rocío.",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "agro_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  (temperatura - ((100 - humedad) / 5)) AS \"Punto de Rocío (ºC)\"\nFROM mediciones_clima\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "📈 Tendencias Climáticas",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 3, "y": 14 },
   "targets": [
    {
     "dataset": "agro_db",
     "rawSql": "SELECT\n  time AS \"time\",\n  temperatura AS \"Temp (ºC)\",\n  humedad AS \"Humedad (%)\"\nFROM mediciones_clima\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  }
 ]
}